# Conexion a la base de datos de mantenimiento
spring.application.name=Proyecto mantenimiento de vehiculos
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/mantenimiento
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA


spring.jpa.show-sql=true
spring.jpa.generate-ddl=true